### ISSUE TITLE
VRAM Viewer: Print value of pixel under cursor

### ISSUE THREAD

**Issue by nickgirardo** [clydeshaffer/GameTankEmulator#20]
Because the gametank has multiple different values that map to the same color under rendering, the VRAM viewer's visual output is not sufficient to fully differentiate grayscale pixels :(

**Comment by clydeshaffer** [comment]
oops i thought this was a PR and got excited but yes good idea

Actually the VRAM Viewer has been in need of an overhaul for a while. The Sprite RAM pages don't really represent the continuity within each page since each bank is represented as a 1x4 column instead of their true 2x2 layout. It's also the last debug window that's not using dear imgui at all.

Besides printing the value under the cursor it'd be good to add zooming in on each one, and indicating the active quadrant of the active bank.
